### ISSUE TITLE
一直报Caused by: java.lang.ClassNotFoundException: Didn't find class "a.RouterMap__TheRouter__，有什么原因吗。

### ISSUE THREAD

**Issue by jkbwfi** [HuolalaTech/hll-wp-therouter-android#108]
java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__1077585027;
2023-09-07 12:14:16.083  1069-1797  System.err              com.chinablue.tv                     W  	at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source:0)
2023-09-07 12:14:16.084  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.asyncInitRouteMap$lambda-4(RouteMap.kt:58)
2023-09-07 12:14:16.085  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.$r8$lambda$OiqKkQwCAH4GRN3KjIF5vkOx1G8(Unknown Source:0)
2023-09-07 12:14:16.085  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt$$ExternalSyntheticLambda0.run(Unknown Source:0)
2023-09-07 12:14:16.085  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
2023-09-07 12:14:16.085  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-09-07 12:14:16.085  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-09-07 12:14:16.086  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.Thread.run(Thread.java:1012)
2023-09-07 12:14:16.086  1069-1797  System.err              com.chinablue.tv                     W  Caused by: java.lang.ClassNotFoundException: Didn't find class "a.RouterMap__TheRouter__1077585027" on path: DexPathList[[zip file "/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/lib/arm64, /data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2023-09-07 12:14:16.087  1069-1797  System.err              com.chinablue.tv                     W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2023-09-07 12:14:16.087  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2023-09-07 12:14:16.088  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-09-07 12:14:16.088  1069-1797  System.err              com.chinablue.tv                     W  	... 8 more
2023-09-07 12:14:16.091  1069-1797  System.err              com.chinablue.tv                     W  java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__1322554853;
2023-09-07 12:14:16.092  1069-1797  System.err              com.chinablue.tv                     W  	at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source:8)
2023-09-07 12:14:16.092  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.asyncInitRouteMap$lambda-4(RouteMap.kt:58)
2023-09-07 12:14:16.092  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.$r8$lambda$OiqKkQwCAH4GRN3KjIF5vkOx1G8(Unknown Source:0)
2023-09-07 12:14:16.092  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt$$ExternalSyntheticLambda0.run(Unknown Source:0)
2023-09-07 12:14:16.093  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
2023-09-07 12:14:16.093  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-09-07 12:14:16.093  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-09-07 12:14:16.094  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.Thread.run(Thread.java:1012)
2023-09-07 12:14:16.095  1069-1797  System.err              com.chinablue.tv                     W  Caused by: java.lang.ClassNotFoundException: Didn't find class "a.RouterMap__TheRouter__1322554853" on path: DexPathList[[zip file "/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/lib/arm64, /data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2023-09-07 12:14:16.095  1069-1797  System.err              com.chinablue.tv                     W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2023-09-07 12:14:16.095 29333-1753  System.out              com.chinablue.tv                     I  [OkHttp] sendRequest>>
2023-09-07 12:14:16.095  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2023-09-07 12:14:16.095 29333-1753  System.out              com.chinablue.tv                     I  [OkHttp] sendRequest<<
2023-09-07 12:14:16.096  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-09-07 12:14:16.096  1069-1797  System.err              com.chinablue.tv                     W  	... 8 more
2023-09-07 12:14:16.098 29333-974   imsdk                   com.chinablue.tv                     I  TIM: |-im_engine_impl.cpp:1840                 OnSynchronizeConversationList           |synchronize conversation complete|task_id:1|error_code:0|error_message:Success
2023-09-07 12:14:16.100  1069-1797  System.err              com.chinablue.tv                     W  java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__1384545045;
2023-09-07 12:14:16.100  1069-1797  System.err              com.chinablue.tv                     W  	at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source:16)
2023-09-07 12:14:16.100  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.asyncInitRouteMap$lambda-4(RouteMap.kt:58)
2023-09-07 12:14:16.101  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.$r8$lambda$OiqKkQwCAH4GRN3KjIF5vkOx1G8(Unknown Source:0)
2023-09-07 12:14:16.101  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt$$ExternalSyntheticLambda0.run(Unknown Source:0)
2023-09-07 12:14:16.101  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
2023-09-07 12:14:16.101  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-09-07 12:14:16.101  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-09-07 12:14:16.102  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.Thread.run(Thread.java:1012)
2023-09-07 12:14:16.102  1069-1797  System.err              com.chinablue.tv                     W  Caused by: java.lang.ClassNotFoundException: Didn't find class "a.RouterMap__TheRouter__1384545045" on path: DexPathList[[zip file "/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/lib/arm64, /data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2023-09-07 12:14:16.102  1069-1797  System.err              com.chinablue.tv                     W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2023-09-07 12:14:16.102  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2023-09-07 12:14:16.102  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-09-07 12:14:16.103  1069-1797  System.err              com.chinablue.tv                     W  	... 8 more
2023-09-07 12:14:16.104 29333-935   AsyncTaskAssistant      com.chinablue.tv                     D  start to run task initChannelsResp
2023-09-07 12:14:16.105  1069-1797  System.err              com.chinablue.tv                     W  java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__1524887566;
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source:24)
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.asyncInitRouteMap$lambda-4(RouteMap.kt:58)
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt.$r8$lambda$OiqKkQwCAH4GRN3KjIF5vkOx1G8(Unknown Source:0)
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.router.RouteMapKt$$ExternalSyntheticLambda0.run(Unknown Source:0)
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-09-07 12:14:16.106  1069-1797  System.err              com.chinablue.tv                     W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-09-07 12:14:16.107  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.Thread.run(Thread.java:1012)
2023-09-07 12:14:16.107  1069-1797  System.err              com.chinablue.tv                     W  Caused by: java.lang.ClassNotFoundException: Didn't find class "a.RouterMap__TheRouter__1524887566" on path: DexPathList[[zip file "/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/lib/arm64, /data/app/~~GfHC87sLAevFMgVM3rRxSA==/com.chinablue.tv-dpjHg-B0qk5UaHXG4Ixu-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2023-09-07 12:14:16.107  1069-1797  System.err              com.chinablue.tv                     W  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2023-09-07 12:14:16.107  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2023-09-07 12:14:16.107  1069-1797  System.err              com.chinablue.tv                     W  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2023-09-07 12:14:16.107  1069-1797  System.err              com.chinablue.tv                     W  	... 8 more

**Comment by jkbwfi** [comment]
合并了一个同事的提交，内容太多，一个个都查过了没发现问题在哪里，请问这个是什么原因导致的呢

**Comment by kymjs** [comment]
使用的是哪个版本

**Comment by jkbwfi** [comment]
> 

抱歉涛哥，回晚了，后面排查到原因了，不是因为这个问题导致的。是因为热修复。我重新描述下
