### ISSUE TITLE
Module内无法正常跳转，跳转的话就会提示have you declared this activity in your AndroidManifest.xml

### ISSUE THREAD

**Issue by VeryCure** [HuolalaTech/hll-wp-therouter-android#140]
你好，我的应用无法在Module内部使用Therouter跳转，我想是不是因为module的类型是library，无法使用therouter这个plugin才导致这个无法跳转的呢？
`android.content.ActivityNotFoundException: Unable to find explicit activity class {com....Activity}; have you declared this activity in your AndroidManifest.xml?
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1770)
                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1087)
                                                                                                    	at android.content.ContextWrapper.startActivity(ContextWrapper.java:443)
                                                                                                    	at com.therouter.router.Navigator$navigation$5.invoke(Navigator.kt:521)
                                                                                                    	at com.therouter.router.Navigator$navigation$5.invoke(Navigator.kt:477)
                                                                                                    	at com.therouter.router.NavigatorKt$routerInterceptor$1.invoke(Navigator.kt:593)
                                                                                                    	at com.therouter.router.NavigatorKt$routerInterceptor$1.invoke(Navigator.kt:592)
                                                                                                    	at com.therouter.router.Navigator.navigation(Navigator.kt:477)
                                                                                                    	at com.therouter.router.Navigator.navigation(Navigator.kt:422)
                                                                                                    	at com.therouter.router.Navigator.navigation(Navigator.kt:417)
                                                                                                    	at com.therouter.router.Navigator.navigation$default(Navigator.kt:416)`

**Comment by kymjs** [comment]
没注册

**Comment by VeryCure** [comment]
但是Activity确实已经添加到AndroidManifest.xml中了

**Comment by SoStrongMan** [comment]
> 但是Activity确实已经添加到AndroidManifest.xml中了

路由path的问题。例如执行跳转的path是/xx/xxx，那么被执行的path必然是/xx/...，两者必须相同

**Comment by kymjs** [comment]
哪个APP，有没有登记 #57
