### ISSUE TITLE
Unable to get provider com.therouter.InnerTheRouterContentProvider

### ISSUE THREAD

**Issue by FiyQiu** [HuolalaTech/hll-wp-therouter-android#167]
tv端在华为魅盒盒子上运行会报错，在其他盒子上正常运行：
![Uploading 11.jpg…]()

**Comment by FiyQiu** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.xx.xx, PID: 20164
                                                                                                    java.lang.RuntimeException: Unable to get provider com.therouter.InnerTheRouterContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.therouter.InnerTheRouterContentProvider" on path: DexPathList[[zip file "/data/app/com.xx.xx-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.xx.xx-1, /system/lib]]
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:4828)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4420)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4360)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:136)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                                                    	at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                                                    	at dalvik.system.NativeStart.main(Native Method)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.therouter.InnerTheRouterContentProvider" on path: DexPathList[[zip file "/data/app/com.xx.xx-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.xx.xx-1, /system/lib]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:4813)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4420) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4360) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loop(Looper.java:136) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                                    	at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                                                                    	at dalvik.system.NativeStart.main(Native Method)

**Comment by FiyQiu** [comment]
盒子：Hisilicon TV-4K (Android 4.4.2, API 19)
