### ISSUE TITLE
一但新增包导入重新编译，再次启动就崩溃，需要清除全部缓存重新编译才正常

### ISSUE THREAD

**Issue by longrenzhut** [HuolalaTech/hll-wp-therouter-android#20]
Process: com.zhongcai.xiaofeng, PID: 7791
    java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__610679138;
        at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source)
        at com.therouter.router.RouteMapKt.asyncInitRouteMap$lambda-4(RouteMap.kt:53)
        at com.therouter.router.RouteMapKt.lambda$OiqKkQwCAH4GRN3KjIF5vkOx1G8(RouteMap.kt)
        at com.therouter.router.-$$Lambda$RouteMapKt$OiqKkQwCAH4GRN3KjIF5vkOx1G8.run(lambda)
        at com.therouter.Task.run(TheRouterThreadPool.kt:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "a.RouterMap__TheRouter__610679138" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.zhongcai.xiaofeng-2/base.apk"],nativeLibraryDirectories=[/data/app/com.zhongcai.xiaofeng-2/lib/x86, /data/app/com.zhongcai.xiaofeng-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]

**Comment by kymjs** [comment]
重复问题   #7
