### ISSUE TITLE
android gradle升级到8.7，targetsdk, compilesdk升级到35,TheRouter升级到1.2.2，使用cn.therouter.agp8，  运行在android6.0,5.1等设备报错

### ISSUE THREAD

**Issue by muzitianya** [HuolalaTech/hll-wp-therouter-android#206]
`java.lang.NoSuchMethodError: No static method addFirst(Ljava/util/List;Ljava/lang/Object;)V in class Lj$/util/List$-EL; or its super classes (declaration of 'j$.util.List$-EL' appears in /data/app/com.aa.bb-1/base.apk:classes2.dex)
                                                                                                    	at com.therouter.TheRouter.init$lambda-2(TheRouter.kt:99)
                                                                                                    	at com.therouter.TheRouter.$r8$lambda$BULbDyOpIbYJtl5j3xPjiy6NiyY(TheRouter.kt)
                                                                                                    	at com.therouter.TheRouter$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
                                                                                                    	at com.therouter.Task.run(TheRouterThreadPool.kt:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                    	at java.lang.Thread.run(Thread.java:818)`

**Comment by kymjs** [comment]
#204
