### ISSUE TITLE
项目升级到Gradle8.6，AGP为8.4.0，TheRouter升级为1.2.3-rc4，可以编译成功，运行时崩溃

### ISSUE THREAD

**Issue by JokeenZhang** [HuolalaTech/hll-wp-therouter-android#207]
```text
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/Unit;
            at com.therouter.InnerTheRouterContentProvider.onCreate(InnerTheRouterContentProvider.kt:19)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:2697)
            at android.content.ContentProvider.attachInfo(ContentProvider.java:2667)
            at android.app.ActivityThread.installProvider(ActivityThread.java:8763)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:8247)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7889)
            at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2640)
            at android.os.Handler.dispatchMessage(Handler.java:108)
            at android.os.Looper.loopOnce(Looper.java:226)
            at android.os.Looper.loop(Looper.java:328)
            at android.app.ActivityThread.main(ActivityThread.java:9217)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.Unit" on path: DexPathList[[dex file "/data/data/com.zokee.pro/code_cache/.overlay/base.apk/classes.dex", zip file "/data/app/~~_db2uIN6_PXoVlrQ_xHQZQ==/com.zokee.pro-GeJrtwmC1oZgiEKdXPY5bg==/base.apk"],nativeLibraryDirectories=[/data/app/~~_db2uIN6_PXoVlrQ_xHQZQ==/com.zokee.pro-GeJrtwmC1oZgiEKdXPY5bg==/lib/arm64, /data/app/~~_db2uIN6_PXoVlrQ_xHQZQ==/com.zokee.pro-GeJrtwmC1oZgiEKdXPY5bg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at com.therouter.InnerTheRouterContentProvider.onCreate(InnerTheRouterContentProvider.kt:19) 
  at android.content.ContentProvider.attachInfo(ContentProvider.java:2697) 
  at android.content.ContentProvider.attachInfo(ContentProvider.java:2667) 
  at android.app.ActivityThread.installProvider(ActivityThread.java:8763) 
  at android.app.ActivityThread.installContentProviders(ActivityThread.java:8247) 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7889) 
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2640) 
  at android.os.Handler.dispatchMessage(Handler.java:108) 
  at android.os.Looper.loopOnce(Looper.java:226) 
  at android.os.Looper.loop(Looper.java:328) 
  at android.app.ActivityThread.main(ActivityThread.java:9217) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
```

**Comment by JokeenZhang** [comment]
Kotlin版本是1.8.0

**Comment by kymjs** [comment]
#204
