### ISSUE TITLE
Unable to get provider com.therouter.InnerTheRouterTrojan

### ISSUE THREAD

**Issue by s1h** [HuolalaTech/hll-wp-therouter-android#24]
版本：1.1.1-rc3
操作：正常编译运行，突然一次运行后报这个错。clean后问题依旧，已将com.therouter.InnerTheRouterTrojan添加至主Dex。
错误详情：
java.lang.RuntimeException: Unable to get provider com.therouter.InnerTheRouterTrojan: java.lang.ClassNotFoundException: Didn't find class "com.therouter.InnerTheRouterTrojan" on path: DexPathList[[zip file "/data/app/com.xxx.xxx-CMaxIG_Y01oTwcsNgQ3s0w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-CMaxIG_Y01oTwcsNgQ3s0w==/lib/arm64, /data/app/com.xxx.xxx-CMaxIG_Y01oTwcsNgQ3s0w==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:8173)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7709)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573)
        at android.app.ActivityThread.access$2600(ActivityThread.java:260)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.therouter.InnerTheRouterTrojan" on path: DexPathList[[zip file "/data/app/com.xxx.xxx-CMaxIG_Y01oTwcsNgQ3s0w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-CMaxIG_Y01oTwcsNgQ3s0w==/lib/arm64, /data/app/com.xxx.xxx-CMaxIG_Y01oTwcsNgQ3s0w==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:8157)

**Comment by kymjs** [comment]
可以反编译确认一下加入主dex 的配置是否生效。另外如果minSdk>21，可以下掉multidex
