### ISSUE TITLE
使用 createFragment 方法创建 Fragment，release 版本会闪退。

### ISSUE THREAD

**Issue by appdev** [HuolalaTech/hll-wp-therouter-android#43]
使用 ViewPager2 承载 Fragment ，使用 `TheRouter.build("app/fragment/mine").createFragment<Fragment>()`创建 Fragment。debug 是正常的，release 下会闪退。具体日志：
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.terek.mtv/cn.terek.mtv.ui.home.HomeActivity}: java.lang.RuntimeException: TheRouter::Navigator cn.terek.mtv.ui.home.fragment.MineFragment is not Fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: TheRouter::Navigator cn.terek.mtv.ui.home.fragment.MineFragment is not Fragment
        at z6.d$a.l(Unknown Source:173)
        at z6.f$a.k(Unknown Source:14)
        at z6.d.a(Unknown Source:141)
        at cn.terek.mtv.ui.home.HomeActivity$b.a(Unknown Source:36)
        at f7.f.a(Unknown Source:20)
        at cn.terek.mtv.ui.home.HomeActivity.F(Unknown Source:12)
        at n2.a.onCreate(Unknown Source:251)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

混淆已经添加

**Comment by kymjs** [comment]
`Fragment`类名不能被混淆了，否则没办法成功创建
