### ISSUE TITLE
An internal error occurred when clicking "测试导航功能" on the demo app

### ISSUE THREAD

**Issue by rayworks** [HuolalaTech/hll-wp-therouter-android#53]
```
2023-02-06 15:12:55.838 16780-16780 TheRouter::RouterInject com.therouter.app                    D  class java.lang.Long do not have @ServiceProvider class. And constructor error::java.lang.Long.<init> []
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  java.lang.NoSuchMethodException: java.lang.Long.<init> []
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at java.lang.Class.getConstructor0(Class.java:2332)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.inject.RouterInject.createDI(RouterInject.kt:101)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.inject.RouterInject.get(RouterInject.kt:54)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.TheRouter.get(TheRouter.kt:169)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.router.autowired.DefaultServiceParser.parse(DefaultServiceParser.kt:11)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.app.navigator.NavigatorTargetActivity__TheRouter__Autowired.autowiredInject(NavigatorTargetActivity__TheRouter__Autowired.java:43)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at a.TheRouterServiceProvideInjecter.autowiredInject(Unknown Source:19)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.TheRouter.inject(TheRouter.kt:193)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.therouter.app.navigator.NavigatorTargetActivity.onCreate(NavigatorTargetActivity.java:79)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.Activity.performCreate(Activity.java:8006)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.Activity.performCreate(Activity.java:7990)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.os.Looper.loop(Looper.java:233)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at android.app.ActivityThread.main(ActivityThread.java:8010)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at java.lang.reflect.Method.invoke(Native Method)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
2023-02-06 15:12:55.838 16780-16780 System.err              com.therouter.app                    W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

`RouteInject` 方法中，"paramsClass" fallback的值在此处 对于`Long`类型并不适用。

```
if (!tClass.isInterface) {
      val paramsClass = if (params.isNotEmpty()) {
          val temp = arrayOfNulls<Class<*>?>(params.size)
          for (i in params.indices) {
              temp[i] = params[i]?.javaClass
          }
          temp
      } else arrayOfNulls<Class<*>?>(0)
      try {
          val constructor: Constructor<*> = tClass.getDeclaredConstructor(*paramsClass)
          if (!constructor.isAccessible) {
              constructor.isAccessible = true
          }
          t = constructor.newInstance(*params) as T
      } catch (e: Exception) {
          debugLog(tClass.toString() + " do not have @ServiceProvider class. And constructor error::" + e.message)
          e.printStackTrace()
      }
  } else {
      debugLog("$tClass is interface, but do not have @ServiceProvider")
  }
```

**Comment by kymjs** [comment]
确实，应该所有封装类都不支持。  
不过作为兜底方案本来也不应该依赖反射创建对象，下个版本会对不支持类型在`debug`环境抛出异常。

**Comment by kymjs** [comment]
此处不支持属于正常逻辑，不影响实际使用
