### ISSUE TITLE
ClassNotFoundException 如何解决

### ISSUE THREAD

**Issue by oOJohn6Oo** [HuolalaTech/hll-wp-therouter-android#89]
### 问题

1. APP 启动最前面会有一些这种报错，路由跳转很多也不可用，参考 #24 及 #18 都没有解决
2. 编译时有警告 `AGPBI: {"kind":"warning","text":"One or more classes has class file version >= 56 which is not officially supported.","sources":[{"file":"xxx525.jar"}],"tool":"D8"}`
3. ` java.lang.IncompatibleClassChangeError`问题
4. 之前看 #50 `trojan` 这个命名不是改过吗？为什么还有？

```

12:12:53.081 TheRouter::init             D  TheRouter init start!
12:12:53.094 TheRouter::init             D  TheRouter.init() method do @FlowTask before task
12:12:53.099 TheRouter::FlowTask         D  Virtual Flow Task TheRouter_Before_Initialization done
12:12:53.101 TheRouter::init             D  TheRouter.init() method do @FlowTask init
12:12:53.101 TheRouter::init             D  TheRouter.init() method do @FlowTask schedule
12:12:53.102 System.err                  W  java.lang.NoClassDefFoundError: Failed resolution of: La/ServiceProvider__TheRouter__1126665995Kt;
12:12:53.102 System.err                  W  	at a.TheRouterServiceProvideInjecter.trojan(Unknown Source:21)
12:12:53.102 System.err                  W  	at com.therouter.inject.RouterInject.asyncInitRouterInject$lambda-0(RouterInject.kt:22)
12:12:53.102 System.err                  W  	at com.therouter.inject.RouterInject.$r8$lambda$-SkUPhBYDcgWIZW2-VO_csVkjN0(Unknown Source:0)
12:12:53.102 System.err                  W  	at com.therouter.inject.RouterInject$$ExternalSyntheticLambda0.run(Unknown Source:4)
12:12:53.102 System.err                  W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
12:12:53.103 System.err                  W  Caused by: java.lang.ClassNotFoundException: Didn't find class "a.ServiceProvider__TheRouter__1126665995Kt" on path: DexPathList[[zip file "/data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.john6.test-bl2QMScW4PSGr5Kzc-dyyQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.john6.test-bl2QMScW4PSGr5Kzc-dyyQ==/lib/arm64, /data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.john6.test-bl2QMScW4PSGr5Kzc-dyyQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product_h/lib64, /system_ext/lib64]]
12:12:53.103 TheRouter::FlowTask         D  Virtual Flow Task TheRouter_Initialization done
12:12:53.103 System.err                  W  java.lang.NoClassDefFoundError: Failed resolution of: La/ServiceProvider__TheRouter__1235101889Kt;
12:12:53.103 System.err                  W  	at a.TheRouterServiceProvideInjecter.trojan(Unknown Source:72)
12:12:53.103 System.err                  W  	at com.therouter.inject.RouterInject.asyncInitRouterInject$lambda-0(RouterInject.kt:22)
12:12:53.103 System.err                  W  	at com.therouter.inject.RouterInject.$r8$lambda$-SkUPhBYDcgWIZW2-VO_csVkjN0(Unknown Source:0)
12:12:53.103 System.err                  W  	at com.therouter.inject.RouterInject$$ExternalSyntheticLambda0.run(Unknown Source:4)
12:12:53.103 System.err                  W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
12:12:53.103 System.err                  W  Caused by: java.lang.ClassNotFoundException: Didn't find class "a.ServiceProvider__TheRouter__1235101889Kt" on path: DexPathList[[zip file "/data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.john6.test-bl2QMScW4PSGr5Kzc-dyyQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.john6.test-bl2QMScW4PSGr5Kzc-dyyQ==/lib/arm64, /data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.john6.test-bl2QMScW4PSGr5Kzc-dyyQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product_h/lib64, /system_ext/lib64]]
12:12:53.104 System.err                  W  java.lang.NoClassDefFoundError: Failed resolution of: La/ServiceProvider__TheRouter__139777712Kt;

...


12:12:53.124 TheRouter::addRouteItem          D  add /group/enter
12:12:53.124 TheRouter::addRouteItem          D  add /group/create
12:12:53.125 System.err                       W  java.lang.IncompatibleClassChangeError: The method 'void a.RouterMap__TheRouter__1137360803$Companion.addRoute()' was expected to be of type static but instead was found to be of type virtual (declaration of 'a.TheRouterServiceProvideInjecter' appears in /data/app/~~DENp0Txn9eXEerQtXgsy1g==/com.intsig.camexam-bl2QMScW4PSGr5Kzc-dyyQ==/base.apk)
12:12:53.125 System.err                       W  	at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source:64)
12:12:53.125 System.err                       W  	at com.therouter.router.RouteMapKt.asyncInitRouteMap$lambda-4(RouteMap.kt:58)
12:12:53.125 System.err                       W  	at com.therouter.router.RouteMapKt.$r8$lambda$OiqKkQwCAH4GRN3KjIF5vkOx1G8(Unknown Source:0)
12:12:53.125 System.err                       W  	at com.therouter.router.RouteMapKt$$ExternalSyntheticLambda0.run(Unknown Source:0)
12:12:53.125 System.err                       W  	at com.therouter.Task.run(TheRouterThreadPool.kt:262)
```

### 版本：

TheRouter: 1.1.4-rc6
Android Gradle Plugin Version: 7.4.2
Gradle Version : 7.5.1

CompileSdk: 33
minSdk: 28

```
Android Studio Giraffe | 2022.3.1 RC 1
Build #AI-223.8836.35.2231.10320515, built on June 14, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true
```

### 使用

没有调用 TheRouter.init()
KSP 依赖正常
clean 后问题依旧
Upgrade Android Gradle Plugin from version 7.1.3 to 7.4.2 问题依旧

**Comment by kymjs** [comment]
请参考项目 demo 的编译环境，重新运行

**Comment by oOJohn6Oo** [comment]
好吧，我发现trojan方法里面做了兼容，会分别尝试带kt和不带kt的类名进行初始化，所以那个报错应该是可以忽略的。但同时我注意到debug包里生成了'LiveLiterals$'前缀的类，不知道对运行有没有影响。

我之前功能异常的原因是：

同一个模块下的三个页面，只有两个被添加到了 map 里，编译时也没有看见相关的 item 添加信息。

请问这种情况一般是什么问题？

**Comment by kymjs** [comment]
> 好吧，我发现trojan方法里面做了兼容，会分别尝试带kt和不带kt的类名进行初始化，所以那个报错应该是可以忽略的。但同时我注意到debug包里生成了'LiveLiterals$'前缀的类，不知道对运行有没有影响。
> 
> 我之前功能异常的原因是：
> 
> 同一个模块下的三个页面，只有两个被添加到了 map 里，编译时也没有看见相关的 item 添加信息。
> 
> 请问这种情况一般是什么问题？

可能是缓存的原因，`clean`以后再试试
