### ISSUE TITLE
增量编译报ASM7错误

### ISSUE THREAD

**Issue by s1h** [HuolalaTech/hll-wp-therouter-android#93]
> Task :app:transformClassesWithTheRouterForSmpadDebug
TheRouter编译插件：cn.therouter:plugin:1.1.4-rc6
当前编译 JDK Version 为::11.0.19
本次是增量编译::true
CHECK_ROUTE_MAP::
CHECK_FLOW_UNKNOW_DEPEND::
---------TheRouter transform start-------------------------------------------
---------TheRouter ASM, spend：38ms----------------------
---------TheRouter get route map from: /assets/therouter/routeMap.json-------
---------TheRouter create new route map, spend:12ms--------------
---------TheRouter check flow task map, spend:3ms--------------
---------TheRouter transform finish, spend:55ms------------------------------------------
error processing CompanyProjects/app/build/intermediates/transforms/TheRouter/smpad/debug/409.jar
java.lang.UnsupportedOperationException: NestHost requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:165)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:553)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:394)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:153)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:100)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
	at com.android.build.gradle.internal.tasks.DesugarIncrementalHelper.lambda$getInitalGraphData$4(DesugarIncrementalHelper.java:146)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by kymjs** [comment]
请使用`1.1.4-rc8`
