### ISSUE TITLE
1.2.0-beta4没有对应的插件

### ISSUE THREAD

**Issue by YeMengLiChou** [HuolalaTech/hll-wp-therouter-android#96]
```

* Exception is:
org.gradle.api.plugins.InvalidPluginException: Could not apply requested plugin [id: 'cn.therouter', version: '1.2.0-beta4'] as it does not provide a plugin with id 'cn.therouter'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.couldNotApply(DefaultPluginRequestApplicator.java:213)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:202)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyLegacyPlugin(DefaultPluginRequestApplicator.java:157)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$300(DefaultPluginRequestApplicator.java:60)
	at
....
```

**Comment by kymjs** [comment]
请按照官网接入文档接入
